'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Matching

    '''<summary>
    '''btnCreate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblKycList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKycList As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvKYCIndividual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvKYCIndividual As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblSurnameKYC_FirstNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSurnameKYC_FirstNameUN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvComparision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvComparision As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblFirstNameKYC_SecondNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstNameKYC_SecondNameUN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvFirstNameKYC_SecondNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvFirstNameKYC_SecondNameUN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblFirstNameKYC_ThirdNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstNameKYC_ThirdNameUN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvFirstNameKYC_ThirdNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvFirstNameKYC_ThirdNameUN As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblFirstNameKYC_FourthNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstNameKYC_FourthNameUN As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gdvFirstNameKYC_FourthNameUN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvFirstNameKYC_FourthNameUN As Global.System.Web.UI.WebControls.GridView
End Class
